baseURL = "https://www.rolandfrogren.com/"
languageCode = "sv"
title = "Roland FrÃ¶gren"
theme = "hugo-theme-console"

#Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = false

  [[params.navlinks]]
  name = "Om/"
  url = "om-mig/"

  [[params.navlinks]]
  name = "Ljud & video/"
  url = "ljud-och-video/"

  [[params.navlinks]]
  name = "Bok/"
  url = "boken/"

  [[params.navlinks]]
  name = "Bild/"
  url = "bilder/"

  [[params.navlinks]]
  name = "Press/"
  url = "press/"
