baseURL = "https://www.rolandfrogren.com/"
languageCode = "sv"
title = "Roland Frögren"
theme = "hugo-theme-console"

[params]
  Description = "Nu finns min bok 'Lättuggat & svårsmält' att köpa."
  Title = "Roland Frögren"
  Image = "balkongbok.jpg"

# Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = false

  [[params.navlinks]]
  name = "Om mig/"
  url = "om-mig/"

  [[params.navlinks]]
  name = "Boken/"
  url = "boken/"

  [[params.navlinks]]
  name = "Bilder/"
  url = "bilder/"

  [[params.navlinks]]
  name = "Texter/"
  url = "texter/"
