baseURL = "https://sharp-kilby-774cb0.netlify.app/"
languageCode = "sv"
title = "Roland FrÃ¶gren"
theme = "hugo-theme-console"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = false

  [[params.navlinks]]
  name = "om mig/"
  url = "ommig/"

  [[params.navlinks]]
  name = "nyheter/"
  url = "nyheter/"

  [[params.navlinks]]
  name = "boken/"
  url = "boken/"

  [[params.navlinks]]
  name = "bilder/"
  url = "bilder/"
